env:
  global:
    - CC_TEST_REPORTER_ID=$CODECLIMATE_REPO_TOKEN
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
language: node_js
node_js:
  - node
notifications:
  email: false
services:
  - postgresql
before_script:
  - npm install -g sequelize
  - psql -c 'drop database if exists testdb;' -U postgres
  - psql -c 'create database testdb;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD '1234';" -U postgres
  - NODE_ENV=test npm run test:db